In [13]:
import json
import csv
import sys

db = 49220

def szures(s):
	s = s.lower()
	s = s.replace("\u00e0", "a")
	s = s.replace("\u0103", "a")
	s = s.replace("\u00e1", "a")
	s = s.replace("\u00e2", "a")
	s = s.replace("\u0391", "a")
	s = s.replace("\u03b1", "a")
	
	s = s.replace("\u00e9", "e")
	s = s.replace("\u00e8", "e")
	
	s = s.replace("\u00ed", "i")
	s = s.replace("\u00ec", "i")
	s = s.replace("\u00ee", "i")
	
	s = s.replace("\u00f3", "o")
	s = s.replace("\u00f6", "o")
	s = s.replace("\u0151", "o")
	s = s.replace("\u039f", "o")
	
	s = s.replace("\u039b", "l")
	
	s = s.replace("\u00fa", "u")
	s = s.replace("\u0171", "u")
	s = s.replace("\u00fc", "u")
	s = s.replace("\u016b", "u")
	
	s = s.replace("\u015f", "s")
	s = s.replace("\u0219", "s")
	
	s = s.replace("\u021b", "t")
	s = s.replace("\u0163", "t")
	
	s = s.replace("\u0e4f", "")
	s = s.replace("\u032f", "")
	s = s.replace("\u0361", "")
	
	s = s.encode('ascii', 'ignore').decode('utf8')
	
	return s

with open("pure.txt") as f:
	s = f.read()
#s = szures(s)
pure_data = json.loads(s)

print(pure_data[:5])

[{'id': 0, 'birth': 'Székelykeresztúr', 'name': '2', 'studwhere': 'Orbán Balázs Gimnázium, Székelykeresztúr', 'livesin': 'szèkelykeresztur, harghita, romania'}, {'id': 1, 'livesin': 'csikszentdomokos', 'other1': 'venczel józsef iskolaközpont   csíkszereda', 'birth': 'Csíkszereda', 'name': '1'}, {'marriedto': 'péterfy eniko', 'studwhere': 'Nincs', 'livesin': 'angyalföld, budapest, hungary', 'workwhere': 'drogmentes világért alapítvány   magyarország', 'name': '2', 'birth': 'Székelyudvarhely', 'id': 2, 'workwhat': 'Igazgató/Vállalkozó'}, {'id': 3, 'name': '2', 'birth': 'Barót', 'livesin': 'budapest, hungary'}, {'birth': 'Sepsiszentgyörgy', 'name': '1', 'marriedto': 'lászló tünde', 'id': 4}]


In [15]:
def livesin(s):
    s = s.lower()
    s = szures(s)
    if "balan" in s \
        or "balanbanya" in s: return u"Balánbánya"
    elif "barot" in s \
        or "baraolt" in s \
        or "nagybacon" in s \
        or "vargyas" in s \
        or "erdofule" in s \
        or "bardocz" in s \
        or "szekelyszaldobos" in s \
        or "olasztelek" in s: return u"Barót"
    elif "csik" in s \
        or "madefalva" in s \
        or "racu" in s \
        or "mindszent" in s \
        or "karcfalva" in s \
        or "szepviz" in s \
        or "madaras" in s \
        or "gyimes" in s \
        or "miercurea ciuc" in s: return u"Csíkszereda"
    elif "gyergyo" in s \
        or "ditro" in s \
        or "borzont" in s \
        or "csomafalva" in s \
        or "alfalu" in s \
        or "szarhegy" in s \
        or "suseni" in s \
        or "tekeropatak" in s \
        or "kilyenfalva" in s \
        or "gyergszentmikls" in s \
        or "ujfal" in s \
        or "gheorgheni" in s: return u"Gyergyószentmiklós"
    elif "tusnad" in s: return u"Tusnádfürdő"
    elif "keresztur" in s \
        or "szentabraham" in s \
        or "szekelyszenterzsebet" in s \
        or "alsbldogfalva" in s \
        or "nagygalambfalva" in s \
        or "simenfalva" in s \
        or "felsoboldogfalva" in s \
        or "cristur" in s: return u"Székelykeresztúr"
    elif "kezdi" in s \
        or "ozsdola" in s \
        or "gelence" in s \
        or "bretcu" in s \
        or "targu secuiesc" in s:return u"Kézdivásárhely"
    elif "kolozsvar" in s \
        or "gherla" in s \
        or "cluj" in s: return u"Kolozsvár"
    elif "sepsiszentgyorgy" in s \
        or "arkos" in s \
        or "sfantu gheorghe" in s: return u"Sepsiszentgyörgy"
    elif "kovaszna" in s \
        or "covasna" in s: return u"Kovászna"
    elif "parajd" in s \
        or "korond" in s \
        or "praid" in s: return u"Parajd"
    elif "regen" in s \
        or "reghin" in s: return u"Szászrégen"
    elif "segesvar" in s \
        or "sighisoara" in s: return u"Segesvár"
    elif "szovata" in s \
        or "sovata" in s: return u"Szováta"
    elif "marosheviz" in s \
        or "borszek" in s \
        or "borsec" in s \
        or "toplita" in s: return u"Maroshévíz"
    elif "mures" in s \
        or "iernut" in s \
        or "radnot" in s \
        or "maros" in s: return u"Marosvásárhely"
    elif "udvarhely" in s \
        or "zetelaka" in s \
        or "mareflava" in s \
        or "rugonfalva" in s \
        or "farkaslaka" in s \
        or "oroszhegy" in s \
        or "bogoz" in s \
        or "odorhei" in s: return u"Székelyudvarhely"
    elif "vlahica" in s \
        or "szentegyhaza" in s\
        or "lovete" in s \
        or "homorod" in s \
        or "kapolnasfalu" in s \
        or "kapolnasfal" in s\
        or "homordalmas" in s \
        or "vlahita" in s: return u"Szentegyháza"
    elif "timisoara" in s \
        or "temes" in s: return u"Temesvár"
    elif "bukarest" in s \
        or "bucharest" in s \
        or "bucuresti" in s: return u"Bukarest"
    elif "szatmar" in s \
        or "satu mare" in s: return u"Szatmárnémeti"
    elif "brasso" in s \
        or "brasov" in s: return u"Brassó"
    elif "arad" in s: return u"Arad"
    elif "sibiu" in s \
        or "szeben" in s: return u"Nagyszeben"
    elif "oradea" in s \
        or "Nagyvárad" in s \
        or "nagyvarad" in s:return u"Nagyvárad"
    elif "iasi" in s \
        or "bacau" in s \
        or "alba iulia" in s \
        or "piatra neamt" in s \
        or "medias" in s \
        or "bistrita" in s \
        or "dej" in s \
        or "constanta" in s \
        or "turda" in s \
        or "deva" in s: return u"Más, Romániából"
    elif "budapest" in s \
        or "hungary" in s \
        or "magyarorszag" in s \
        or "dunakeszi" in s \
        or "sopron" in s \
        or "szeged" in s \
        or "nyiregyhaza" in s \
        or "kecskemet" in s \
        or "pilis" in s \
        or "pecs" in s \
        or "szekesfehervar" in s \
        or "kecskemet" in s \
        or "budaors" in s \
        or "tatabanya" in s \
        or "veszprem" in s \
        or "debrecen" in s \
        or "oroszlany" in s \
        or "szombathely" in s \
        or "mosonmagyarovar" in s \
        or "kaposvar" in s \
        or "erd" in s \
        or "lajosmizse" in s \
        or "szigetszentmiklos" in s \
        or "gyor" in s: return u"Magyarország"
    elif "germany" in s \
        or "nuremberg" in s \
        or "nemetorszag" in s: return u"Németország"
    elif "italy" in s \
        or "italia" in s \
        or "olaszorszag" in s: return u"Olaszország"
    elif "austria" in s\
        or "ausztria" in s\
        or "vienna" in s: return u"Ausztria"
    elif "norway" in s \
        or "norvegia" in s: return u"Norvégia"
    elif "london" in s \
        or "liverpool" in s \
        or "anglia" in s\
        or "united kingdom" in s:return u"Anglia"
    elif "schwitzerland" in s \
        or "switzerland" in s \
        or "svajc" in s \
        or "zurich" in s:return u"Svájc"
    elif "sweden" in s \
        or "svedorszag" in s: return u"Svédország"
    elif "spain" in s \
           or "spanyolorszag" in s : return u"Spanyolország"
    elif "netherland" in s \
        or "hollandia" in s: return u"Hollandia"
    elif "denmark" in s \
        or "dania" in s: return u"Dánia"
    elif "los angeles" in s \
        or "california" in s \
        or "hollywood" in s\
        or "amerika" in s \
        or "florida" in s \
        or "usa" in s \
        or "new york" in s: return u"USA"
    elif "canada" in s \
        or "toronto" in s : return "Canada"
    elif "ireland" in s \
        or "irorszag" in s: return u"Írország"
    elif "poland" in s \
        or "lengyelorszag" in s: return u"Lengyelország"
    elif "france" in s \
        or "francia" in s: return u"Franciaország"
    else:
        return u"Más"
    
lakhely = sorted(["Arad", "Balánbánya", "Brassó","USA", "Dánia", "Hollandia", "Spanyolország", "Svédország", "Svájc", "Anglia", "Norvégia", "Ausztria", "Olaszország",
           "Magyaroszág", "Németország", "Szatmárnémeti", "Bukarest", "Temesvár", "Más, Romániából",
           "Szentegyháza", "Székelyudvarhely", "Segesvár", "Maroshévíz", "Csíkszereda", "Barót", "Franciaország", "Más",
          "Gyergyószentmiklós", "Sepsiszentgyörgy", "Marosvásárhely", "Kolozsvár", "Szászrégen", "Parajd", "Kovászna", "Canada",
           "Kézdivásárhely", "Tusnádfürdő", "Székelykeresztúr", "Szováta", "Írország", "Nagyszeben", "Lengyelország"])

def szukit(s):
    if "Tusnádfürdő" in s or \
        "Brassó" in s or \
        "Temesvár" in s or \
        "Bukarest" in s or \
        "Arad" in s or \
        "Nagyszeben" in s or \
        "Nagyvárad" in s or \
        "Szatmárnémeti" in s or \
        "Más Romániából" in s : return u"Más románia város"
    elif "USA" in s or \
        "Canada" in s: return u"Amerika"
    elif "Dánia"in s or \
        "Anglia" in s or \
        "Hollandia" in s or \
        "Olaszország" in s or \
        "Spanyolország" in s or \
        "Svédország" in s or \
        "Svájc" in s or \
        "Németország" in s or \
        "Franciaország" in s or \
        "Ausztria" in s or \
        "Norvégia" in s or \
        "Írország" in s or \
        "Lengyelország" in s: return u"Európa"
    else:
        return s;
    

        

szukitett = sorted(["Más románia város", "Balánbánya","Amerika", "Európa","Magyarország",
           "Szentegyháza", "Székelyudvarhely", "Segesvár", "Maroshévíz", "Csíkszereda", "Barót", "Más",
          "Gyergyószentmiklós", "Sepsiszentgyörgy", "Marosvásárhely", "Kolozsvár", "Szászrégen", "Parajd", "Kovászna",
           "Kézdivásárhely", "Székelykeresztúr", "Szováta"])

print(lakhely)
print(len(lakhely))

db = 0
for d in pure_data:
    if "livesin" in d:
        d["livesin"] = livesin(d["livesin"])
        
for d in pure_data:
    if "livesin" in d:
        d["livesin"] = szukit(d["livesin"])
        
print("---")
print(szukitett)


['Anglia', 'Arad', 'Ausztria', 'Balánbánya', 'Barót', 'Brassó', 'Bukarest', 'Canada', 'Csíkszereda', 'Dánia', 'Franciaország', 'Gyergyószentmiklós', 'Hollandia', 'Kolozsvár', 'Kovászna', 'Kézdivásárhely', 'Lengyelország', 'Magyaroszág', 'Maroshévíz', 'Marosvásárhely', 'Más', 'Más, Romániából', 'Nagyszeben', 'Norvégia', 'Németország', 'Olaszország', 'Parajd', 'Segesvár', 'Sepsiszentgyörgy', 'Spanyolország', 'Svájc', 'Svédország', 'Szatmárnémeti', 'Szentegyháza', 'Szováta', 'Szászrégen', 'Székelykeresztúr', 'Székelyudvarhely', 'Temesvár', 'Tusnádfürdő', 'USA', 'Írország']
42
---
['Amerika', 'Balánbánya', 'Barót', 'Csíkszereda', 'Európa', 'Gyergyószentmiklós', 'Kolozsvár', 'Kovászna', 'Kézdivásárhely', 'Magyarország', 'Maroshévíz', 'Marosvásárhely', 'Más', 'Más románia város', 'Parajd', 'Segesvár', 'Sepsiszentgyörgy', 'Szentegyháza', 'Szováta', 'Szászrégen', 'Székelykeresztúr', 'Székelyudvarhely']


In [16]:
holel = {}
for d in pure_data:
    if "livesin" in d:
        l = d["livesin"]
        if l in holel:
            holel[l] = holel[l] + 1
        else:
            holel[l] = 1

print(sorted(holel.items(), key=lambda x: x[1], reverse=True))

[('Más', 9555), ('Kolozsvár', 5081), ('Marosvásárhely', 3902), ('Sepsiszentgyörgy', 2904), ('Magyarország', 2614), ('Csíkszereda', 2369), ('Székelyudvarhely', 2021), ('Kézdivásárhely', 1965), ('Gyergyószentmiklós', 1806), ('Szentegyháza', 1505), ('Székelykeresztúr', 1436), ('Szászrégen', 1273), ('Maroshévíz', 1174), ('Barót', 1146), ('Segesvár', 1082), ('Kovászna', 1078), ('Szováta', 1025), ('Parajd', 896), ('Balánbánya', 646), ('Amerika', 137)]


In [17]:
lives = {}
birth = {}
for d in pure_data:
    if "livesin" in d:
        if "workwhat" in d:
            if d["workwhat"] == 'Informatikus':
                l = d["livesin"]
                b = d["birth"]
                if l in lives:
                    lives[l] = lives[l] + 1
                else:
                    lives[l] = 1
                if b in birth:
                    birth[b] = birth[b] + 1
                else:
                    birth[b] = 1
print(lives)
print("---")
print(birth)

{'Magyarország': 17, 'Kolozsvár': 124, 'Más': 30, 'Marosvásárhely': 47, 'Sepsiszentgyörgy': 11, 'Maroshévíz': 1, 'Székelyudvarhely': 6, 'Szászrégen': 3, 'Csíkszereda': 6, 'Kézdivásárhely': 3, 'Szentegyháza': 2, 'Székelykeresztúr': 2, 'Barót': 4, 'Szováta': 2, 'Segesvár': 1, 'Balánbánya': 1, 'Gyergyószentmiklós': 3, 'Amerika': 1}
---
{'Marosvásárhely': 54, 'Kolozsvár': 59, 'Gyergyószentmiklós': 17, 'Segesvár': 12, 'Sepsiszentgyörgy': 12, 'Szászrégen': 21, 'Csíkszereda': 25, 'Barót': 4, 'Kovászna': 15, 'Maroshévíz': 6, 'Székelyudvarhely': 12, 'Kézdivásárhely': 8, 'Szentegyháza': 5, 'Székelykeresztúr': 8, 'Balánbánya': 3, 'Szováta': 3}


In [22]:
def chord_diagram_json_maker(workwhat):
    flare = {}
    for d in pure_data:
        if "livesin" in d:
            if "workwhat" in d:
                if d["workwhat"] == workwhat:
                    birth = d["birth"]
                    lives = d["livesin"]
                    if birth not in flare:
                        flare[birth] = {}
                    if lives not in flare[birth]:
                        flare[birth][lives] = 1
                    else:
                        flare[birth][lives] = flare[birth][lives] + 1
    return flare
                
flare = chord_diagram_json_maker('Sportoló/Edző/Bíró')
print(flare)

{'Marosvásárhely': {'Csíkszereda': 1, 'Szováta': 1, 'Marosvásárhely': 16, 'Kolozsvár': 3, 'Más': 2, 'Magyarország': 3}, 'Kovászna': {'Sepsiszentgyörgy': 9, 'Más': 10, 'Magyarország': 1, 'Kolozsvár': 1, 'Kézdivásárhely': 6, 'Csíkszereda': 2, 'Gyergyószentmiklós': 1}, 'Szászrégen': {'Marosvásárhely': 1, 'Más': 5, 'Szászrégen': 7}, 'Kolozsvár': {'Kolozsvár': 35, 'Más': 11, 'Székelyudvarhely': 1}, 'Sepsiszentgyörgy': {'Más': 5, 'Csíkszereda': 2, 'Magyarország': 4, 'Sepsiszentgyörgy': 13, 'Barót': 1, 'Marosvásárhely': 1, 'Kolozsvár': 1, 'Gyergyószentmiklós': 1}, 'Szentegyháza': {'Szentegyháza': 3, 'Más': 2, 'Magyarország': 1}, 'Székelyudvarhely': {'Más': 5, 'Székelyudvarhely': 12, 'Kolozsvár': 1, 'Csíkszereda': 2, 'Székelykeresztúr': 1, 'Marosvásárhely': 2}, 'Gyergyószentmiklós': {'Kolozsvár': 4, 'Magyarország': 1, 'Gyergyószentmiklós': 5, 'Csíkszereda': 3, 'Marosvásárhely': 1, 'Más': 1}, 'Balánbánya': {'Más': 5, 'Balánbánya': 1, 'Csíkszereda': 3}, 'Barót': {'Magyarország': 1, 'Más': 1, 'Cs

In [21]:
def chord_diagram_matrix_maker(workwhat):
    flare = chord_diagram_json_maker(workwhat);
    matrix = [[0 for i in range(len(szukitett))] for j in range(len(szukitett))]
    
    for b in flare:
        for l in flare[b]:
            matrix[szukitett.index(b)][szukitett.index(l)] = flare[b][l]
    
    return matrix

m = numpy.array(chord_diagram_matrix_maker('Fodrász/Kozmetikus'))
print(m)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  9  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0 27  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  6  1  0  0  3  0  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  5  1  0  0  1  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0 14  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [12]:
import numpy
foglalkozasok = ["Fodrász/Kozmetikus", "Mérnök/Műépítész", "Ügyvéd/Közjegyző", "Tanár/Kutató", "Tanuló","Informatikus", "Sportoló/Edző/Bíró", "Orvos/Gyógyszerész", "Irodai_alkalmazott", "Eladó/Ügynök/Recepciós", "Bartender/Pincér/Szakács", "Médiamunkás", "Zenész/Művész", "Igazgató/Vállalkozó", "Nevelő/Au Pair/Önkéntes", "Szakmunkás", "Raktáros/Logisztikus", "Sofőr", "Közalkalmazott", "Édesanya/Háztartásbeli", "None", "Más"]

for f in foglalkozasok:
    m = chord_diagram_matrix_maker(f)
    m = numpy.array(m)
    szam = m.sum(axis = 1)
    print(f)
    print(szam)
    print(m)
    print("---------------------------------------------------------------")

Fodrász/Kozmetikus
[ 0  1  1 11  0  6 32 14 11  0  4 17  0  0  1  9 10  0  3 14  3 20]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  9  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0 27  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  6  1  0  0  3  0  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  5  1  0  0  1  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0 14  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0

Közalkalmazott
[ 0  1  5  1  0 10  6  6  4  0  1  8  0  0  2  1  7  6  4  1  9  8]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 6 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 5 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 1 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 5 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 6 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 4 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 